(IN-PACKAGE #:DEMO-DRAWING)
(GEN-SVG
 (:G :ID "group1"
  (:RECT :X 228 :Y 82 :HEIGHT 100 :WIDTH 40 :FILL
   (META "#2fc02f" :IF (:TYPE :COLOR-PICKER :OUTPUT :HTML-RGB-STRING)))
  (:ELLIPSE :CX 245 :FILL
   (META "#CC4B4B" :IF
    (:TYPE :SELECT :OPTIONS
     ((:VALUE "#CC4B4B" :TITLE "Faded Red")
      (:VALUE "#C80000" :TITLE "Dark Red"))))
   :CY 320 :RX 100 :RY 100))
 (META
  (:G :ID "group2"
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX 453.0
    :CY 300.0)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX
    452.20193 :CY 303.42932)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX 447.6961
    :CY 305.03406)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX
    442.55453 :CY 301.0613))
  :MODE
  (:FORMAT :SPIRAL-POINTS-EXPAND :MODEL
   (SPIRAL-POINTS 450 300
    (META
     ((META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :IF (:REMOVABLE T :TITLE "Small Green Circle" :TYPE :ITEM))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :IF (:TYPE :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :IF (:REMOVABLE T :TITLE "Small Green Circle" :TYPE :ITEM))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :IF (:TYPE :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :IF (:REMOVABLE T :TITLE "Small Green Circle" :TYPE :ITEM))
      (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
       :IF (:TYPE :ITEM :TITLE "Big Blue Circle" :REMOVABLE T))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :IF (:REMOVABLE T :TITLE "Small Green Circle" :TYPE :ITEM))
      (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
       :IF (:TYPE :ITEM :TITLE "Big Blue Circle" :REMOVABLE T))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :IF (:REMOVABLE T :TITLE "Small Green Circle" :TYPE :ITEM)))
     :IF
     (:OPTIONS
      ((:VALUE
        (META
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00")) :IF
         (:TYPE :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
        :TITLE "Small Green Circle")
       (:VALUE
        (META
         ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE")) :IF
         (:TYPE :ITEM :TITLE "Big Blue Circle" :REMOVABLE T))
        :TITLE "Big Blue Circle"))
      :REMOVABLE NIL :FILL-BY :SELECT :TYPE :LIST))))))
(LET ((A 1) (B 2))
  (+ (* A 3) (+ B 1)))
(LIST #\a T NIL (CAR (CDR (LIST 1 2))))
