(IN-PACKAGE #:DEMO-DRAWING)
(GEN-SVG
 (:G :ID "group1"
  (:RECT :X 228 :Y 82 :HEIGHT 100 :WIDTH 40 :FILL
   (META "#0fc50f" :MODE (:OUTPUT :HTML-RGB-STRING :VIEW :COLOR-PICKER)))
  (:ELLIPSE :CX 245 :FILL
   (META "#CC4B4B" :MODE
    (:OPTIONS
     ((:TITLE "Faded Red" :VALUE "#CC4B4B")
      (:TITLE "Dark Red" :VALUE "#C80000"))
     :VIEW :SELECT))
   :CY 320 :RX 100 :RY 100))
 (META
  (:G :ID "group2"
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX 453.0
    :CY 300.0)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX
    452.20193 :CY 303.42932)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX 447.6961
    :CY 305.03406)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX
    442.55453 :CY 301.0613)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX 443.322
    :CY 292.26807)
   (:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE" :CX 453.9369
    :CY 286.69128)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX 468.1028
    :CY 294.73196)
   (:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE" :CX
    469.30896 :CY 316.82675)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX
    444.93762 :CY 334.4226)
   (:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE" :CX
    406.93576 :CY 319.47864)
   (:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00" :CX
    396.12573 :CY 265.07004))
  :MODE
  (:MODEL
   (SPIRAL-POINTS 450 300
    (META
     ((META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :VIEW :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :VIEW :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :VIEW :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
      (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
       :MODE
       (:VIEW :ITEM :TITLE "Big Blue Circle" :REMOVABLE T :MODEL
        ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
        :VALUE NIL))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
      (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
       :MODE
       (:VIEW :ITEM :TITLE "Big Blue Circle" :REMOVABLE T :MODEL
        ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
        :VALUE NIL))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
      (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
       :MODE
       (:VIEW :ITEM :TITLE "Big Blue Circle" :REMOVABLE T :MODEL
        ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
        :VALUE NIL))
      (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
       :MODE
       (:VALUE NIL :MODEL
        ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM)))
     :MODE
     (:VALUE NIL :MODEL
      ((META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :VIEW :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
       (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
       (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :VIEW :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
       (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :VIEW :ITEM :TITLE "Small Green Circle" :REMOVABLE T))
       (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
       (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
        :MODE
        (:VIEW :ITEM :TITLE "Big Blue Circle" :REMOVABLE T :MODEL
         ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
         :VALUE NIL))
       (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
       (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
        :MODE
        (:VIEW :ITEM :TITLE "Big Blue Circle" :REMOVABLE T :MODEL
         ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
         :VALUE NIL))
       (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM))
       (META ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
        :MODE
        (:VIEW :ITEM :TITLE "Big Blue Circle" :REMOVABLE T :MODEL
         ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
         :VALUE NIL))
       (META ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
        :MODE
        (:VALUE NIL :MODEL
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :REMOVABLE T :TITLE "Small Green Circle" :VIEW :ITEM)))
      :VIEW :LIST :FILL-BY :SELECT :REMOVABLE NIL :OPTIONS
      ((:TITLE "Small Green Circle" :VALUE
        (META
         ((:CIRCLE :R 3 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#88AA00"))
         :MODE (:VIEW :ITEM :TITLE "Small Green Circle" :REMOVABLE T)))
       (:TITLE "Big Blue Circle" :VALUE
        (META
         ((:CIRCLE :R 5 :STROKE-WIDTH 2 :STROKE "#E3DBDB" :FILL "#87AADE"))
         :MODE (:VIEW :ITEM :TITLE "Big Blue Circle" :REMOVABLE T)))))))
   :FORMAT :SPIRAL-POINTS-EXPAND :VALUE NIL)))
(LET ((A 1) (B 2))
  (+ (* A 3) (+ B 1)))
(LIST #\a T NIL (CAR (CDR (LIST 1 2))))
