;;;; seed.ui-spec.stage-controls.document.base.lisp

(in-package #:seed.ui-spec.stage.base)

(defmacro stage-controls-document-base (meta-symbol spec-symbol params-symbol output-symbol)
  (declare (ignorable spec-symbol))
  `(((eq :doc-mark-bold (first ,params-symbol))
     (cons `(,',meta-symbol :bold :if (:interaction :doc-mark-bold))
	   ,output-symbol))
    ((eq :doc-mark-italic (first ,params-symbol))
     (cons `(,',meta-symbol :italic :if (:interaction :doc-mark-italic))
	   ,output-symbol))
    ((eq :doc-node-pgraph (first ,params-symbol))
     (cons `(,',meta-symbol :paragraph :if (:interaction :doc-node-pgraph))
	   ,output-symbol))
    ((eq :doc-node-quote (first ,params-symbol))
     (cons `(,',meta-symbol :quote :if (:interaction :doc-node-quote))
	   ,output-symbol))
    ((eq :doc-node-points (first ,params-symbol))
     (cons `(,',meta-symbol :points :if (:interaction :doc-node-points))
	   ,output-symbol))
    ((eq :doc-node-count (first ,params-symbol))
     (cons `(,',meta-symbol :count :if (:interaction :doc-node-count))
	   ,output-symbol))))
