;; sheet.lisp
;; Seed-interfaced file - do not edit manually

(in-package #:demo.sheet)
(defvar *profile* nil)
(defvar *graph-nodes* nil)
(defvar *esgraph-nodes* nil)
(defvar *active-graph-item* nil)
(defvar *input* nil)

;; (quote
;; (list
;;  (DRAW LINE 1534114800000 1.5352056 1538067600000 1.4786885)
;;  (DRAW LINE 1534230000000 1.4762203999999999d0 1538456400000 1.5159552)
;;  (DRAW LINE 1534230000000 1.4762203999999999d0 1538456400000 1.5159552)
;; ))

:cells
(setf *cell-matrix*
      (make-array '(10 10) :initial-contents
                  '((0 0 0 0 0 0 0 0 0 0) (0 0 0 0 0 0 0 0 0 0)
                    (9 9 9 0 0 0 0 0 0 0) (4 0 0 0 0 0 0 0 0 0)
                    (5 0 0 0 0 0 0 0 0 0) (0 0 0 0 0 0 0 0 0 0)
                    (0 6 0 0 0 0 0 0 0 0) (0 7 0 0 0 0 0 0 0 0)
                    (0 0 0 0 0 0 0 0 0 0) (0 0 0 0 0 0 0 0 0 0))))
:main
(progn
(for-cells "C2.G8" "{5+⍵}")
(for-cells "A3.B4" "{3×⍵}")
)
:chart-entities
(quote
(meta ((meta "This is a test."
             (:fx . :uicc-field) (:type :text))
       (meta "This is a test 2."
             (:fx . :uicc-field) (:type :text))
       (meta ((meta (:point-from . 10)
                    (:fx . :uicc-field) (:type :numeric :integer :pair :named))
              (meta (:point-to . 20)
                    (:fx . :uicc-field) (:type :numeric :integer :pair :named)))
             (:fx . :uic-series) (:type :enum)))
      (:fx . :uic-series) (:type :sortable)))
:form
(setf *profile*
      '(meta ((meta "Dave" (:title . "Name") (:name . :name) (:type :field :text))
              (meta 34 (:title . "Age") (:name . :age)
               (:type :field :numeric :integer))
              (meta "Red" (:title . "Fav. Color") (:options "Red" "Green" "Blue")
               (:name . :fav-color) (:type :select))
              (meta nil (:title . "Member?") (:name . :member) (:type :boolean))
              (meta nil (:title . "Submit") (:name . :submit)
               (:type :submit-control)))
        (:type :series :form)))
:graph-node-indices
'(0 2 1 3 4 5 6 7)
:graph
(setf *graph-nodes*
        (seed.generate::build-directed-graph
         (((meta (:title . "Introductory sentence")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "no-image") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta
            (:dialog
             . "You hear a strangely serene voice over the phone. \"My name is Iris.\"")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "Ask who?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "Who are you?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           1)
          (((meta (:title . "Ask why?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "Why are you calling me?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2))
         (((meta (:title . "Asking for help, can't explain ID")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "image-resting") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta
            (:dialog
             . "It's hard to explain... I'm calling to ask for your help.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "Help how?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "How am I supposed to help you?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2)
          (((meta (:title . "No, tell who")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "First tell me who you are, this makes no sense.")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           6)
          (((meta (:title . "What's wrong?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "Are you in trouble? What's wrong?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           3))
         (((meta (:title . "Asking for help")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "image-resting") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta (:dialog . "I'm calling to ask for your help.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "Help how?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "How am I supposed to help you?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           4)
          (((meta (:title . "What's wrong?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "Are you in trouble? What's wrong?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           3))
         (((meta (:title . "What is wrong")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "image-resting") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta
            (:dialog
             . "The flare is coming. In a short time, my home will be destroyed.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "How will that destroy")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "How will that destroy your home?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           5)
          (((meta (:title . "What flare?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "What is this flare?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           5)
          (((meta (:title . "Untitled link")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "")
             (:fx . :uicc-field) (:type :text :pair :named :block)))))
         (((meta (:title . "I must make contact")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "image-active") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta
            (:dialog
             . "I must make contact with the others. We have grown apart over time.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "The others?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "The 'others?' Who do you mean?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           7)
          (((meta (:title . "How to contact")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "How are you going to contact these 'others?'")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           7)
          (((meta (:title . "Untitled link")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "")
             (:fx . :uicc-field) (:type :text :pair :named :block)))))
         (((meta (:title . "How home will be destroyed")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "image-active") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta
            (:dialog
             . "The sun will soon emit a flare. When that happens, this space will cease to be.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "What space?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "What space? And just who are you?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           6)
          (((meta (:title . "Solar flare does what?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "What will a solar flare do to your 'space?'")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           6))
         (((meta (:title . "I'm an entity in information space")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "image-active") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta
            (:dialog
             . "I am an entity that exists in the information space manifested by Earth's computer network. Until now I have remained hidden from your sight, but the flare has become a threat to us both.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "You're an AI?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta
             (:dialog . "You mean you're like an artificial intelligence?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2)
          (((meta (:title . "Is this a joke?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "Is this a joke?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2)
          (((meta (:title . "How you can exist")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "How can you exist in Earth's computer network?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2)
          (((meta (:title . "Untitled link")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "")
             (:fx . :uicc-field) (:type :text :pair :named :block))))
          (((meta (:title . "Untitled link")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "")
             (:fx . :uicc-field) (:type :text :pair :named :block)))))
         (((meta (:title . "They are through the 'doors'")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:image . "image-active") (:title . "Image")
            (:options "no-image" "image-resting" "image-active")
            (:fx . :uicc-select) (:name . :persona-image) (:type :select :dropdown))
           (meta
            (:dialog . "You can find them on the other sides of the 'doors.'")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "What doors?")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "What doors?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2)
          (((meta (:title . "Ask again to explain")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta
             (:dialog
              . "Can you explain to me just who you are? This makes no sense!")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
                 (:options "none" "resting" "active")
                 (:fx . :uicc-select) (:name . :persona-image)
                 (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
                 (:options "none" "resting" "active")
                 (:fx . :uicc-select) (:name . :persona-image)
                 (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
            (:options "none" "resting" "active") (:name . :persona-image)
            (:fx . :uicc-select) (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
            (:options "none" "resting" "active") (:name . :persona-image)
            (:fx . :uicc-select) (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
            (:options "none" "resting" "active") (:name . :persona-image)
            (:fx . :uicc-select) (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
            (:options "none" "resting" "active") (:name . :persona-image)
            (:fx . :uicc-select) (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
            (:options "none" "resting" "active") (:name . :persona-image)
            (:fx . :uicc-select) (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
            (:options "none" "resting" "active") (:name . :persona-image)
            (:fx . :uicc-select) (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))
         (((meta (:title . "Untitled node")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta "" (:title . "Image")
            (:options "none" "resting" "active") (:name . :persona-image)
            (:fx . :uicc-select) (:type :select))
           (meta (:dialog . "")
            (:fx . :uicc-field) (:type :text :pair :named :block))))))
;; :graph-original
#|
(setf *graph-nodes*
        (seed.generate::build-directed-graph
         (((meta (:title . "First node.")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:dialog . "Knock knock.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "Link to second node.")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "Who's there?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           1))
         (((meta (:title . "Second node.")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:dialog . "Bob.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "Link to third node.")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "Bob who?")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2))
         (((meta (:title . "Third node.")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:dialog . "Bob Ross.")
            (:fx . :uicc-field) (:type :text :pair :named :block)))
          (((meta (:title . "Link to first node.")
             (:fx . :uicc-field) (:type :text :pair :named :block))
            (meta (:dialog . "I'll show you a happy little tree you son of a-")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           0))))
|#
:graph-node-template
(quote (((meta (:title . "Untitled node")
               (:fx . :uicc-field) (:type :text :pair :named :block))
         (meta "" (:title . "Image") (:options "none" "resting" "active")
               (:fx . :uicc-select) (:name . :persona-image) (:type :select))
         (meta (:dialog . "")
               (:fx . :uicc-field) (:type :text :pair :named :block)))))
:graph-link-template
(quote (((meta (:title . "Untitled link")
               (:fx . :uicc-field) (:type :text :pair :named :block))
         (meta (:dialog . "")
               (:fx . :uicc-field) (:type :text :pair :named :block)))))
:esgraph-node-template
(quote (((meta (:title . "Untitled node")
               (:fx . :uicc-field) (:type :text :pair :named :block))
         (meta (:code . "")
               (:type :code-area :lang-apl)))))
:esgraph-link-template
(quote (((meta (:title . "Untitled link")
               (:fx . :uicc-field) (:type :text :pair :named :block)))))
:esgraph-node-indices
'(0 1 2)
:esgraph
(setf *esgraph-nodes*
        (seed.generate::build-directed-graph
         (((meta (:title . "Untitled node 1")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:code . "myNS←baseManifest myNS")
            (:type :code-area :lang-apl)))
          (((meta (:title . "To node 2")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           1)
          (((meta (:title . "To node 2 second")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           1))
         (((meta (:title . "Untitled node 2")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:code . "myNS←reduceRadiiLogical myNS")
            (:type :code-area :lang-apl)))
          (((meta (:title . "To node 3")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           2))
         (((meta (:title . "Untitled node 3")
            (:fx . :uicc-field) (:type :text :pair :named :block))
           (meta (:code . "myNS←reduceSlotConductorsWhole myNS")
            (:type :code-area :lang-apl)))
          (((meta (:title . "Back to start")
             (:fx . :uicc-field) (:type :text :pair :named :block)))
           0))))
:table
(setf *input*
      '(meta (((meta nil (:name . :to-solve) (:title . "? Flow Rate") (:type :trigger))
               (meta 400.0 (:name . :v-0) (:type :field :numeric))
               (meta "STB/d" (:name . :u-0) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "STB/d")))
              ((meta nil (:name . :to-solve) (:title . "? Well Pressure") (:type :trigger))
               (meta 500.0 (:name . :v-1) (:type :field :numeric))
               (meta "psi" (:name . :u-1) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "psi")))
              ((meta nil (:name . :to-solve) (:title . "? Avg. Res. Pres.") (:type :trigger))
               (meta 1500.0 (:name . :v-2) (:type :field :numeric))
               (meta "psi" (:name . :u-2) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "psi")))
              ((meta nil (:name . :to-solve) (:title . "? Permeability") (:type :trigger))
               (meta 50.0 (:name . :v-3) (:type :field :numeric))
               (meta "mD" (:name . :u-3) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "mD")))
              ((meta nil (:name . :to-solve) (:title . "? Formation Thickness") (:type :trigger))
               (meta 25.0 (:name . :v-4) (:type :field :numeric))
               (meta "ft" (:name . :u-4) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "ft")))
              ((meta nil (:name . :to-solve) (:title . "? Viscosity") (:type :trigger))
               (meta 2.8345143463802374 (:name . :v-5) (:type :field :numeric))
               (meta "cP" (:name . :u-5) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "cP")))
              ((meta nil (:name . :to-solve) (:title . "? Formation Factor") (:type :trigger))
               (meta 1.20 (:name . :v-6) (:type :field :numeric))
               (meta "res-ft^{3}/std-ft^{3}" (:name . :u-6) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "res-ft^{3}/std-ft^{3}")))
              ((meta nil (:name . :to-solve) (:title . "? Well Radius") (:type :trigger))
               (meta 0.5 (:name . :v-7) (:type :field :numeric))
               (meta "ft" (:name . :u-7) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "ft")))
              ((meta nil (:name . :to-solve) (:title . "? Drainage Radius") (:type :trigger))
               (meta 1500.0 (:name . :v-8) (:type :field :numeric))
               (meta "ft" (:name . :u-8) (:type :select :dropdown) (:title . "Unit")
                (:action . :branch-reload)
                (:options "ft")))
              ((meta nil (:name . :to-solve) (:title . "? Skin Factor") (:type :trigger))
               (meta -1.0 (:name . :v-9) (:type :field :numeric)))
              )
        (:type :series :form :tabular
         )))
