(META
 ((META :PORTAL.DEMO1 :ATOM (:IF (:TYPE :PORTAL-NAME)) :IF
   (:ENCLOSE :ENCLOSE-OVERVIEW :FILL :FILL-OVERVIEW :NAME :PORTAL-SPECS :LAYOUT
    :COLUMN :BREADTH :SHORT :TYPE :VISTA))
  (META (:DEMO-SHEET :DEMO-DRAWING) :EACH (:IF (:INTERACTION :SELECT-SYSTEM))
   :IF (:INDEX -1 :TYPE :PORTAL-SYSTEM-LIST)))
 :ATOM (:IF (:TYPE :PORTAL-NAME)) :IF
 (:ENCLOSE :ENCLOSE-OVERVIEW :FILL :FILL-OVERVIEW :NAME :PORTAL-SPECS :LAYOUT
  :COLUMN :BREADTH :SHORT :TYPE :VISTA))
