(in-package #:abcd)

:properties
(list :name "USDJPY proto" :description "This is an analysis of USDJPY currency pair.")

:chart-entities
(fx
 (chart-view chart-test-usdjpy
  (fx "/tmp/USDJPY.data.csv" (:fx :uicc-field) (:type :text))
  (fx
   (essource :file-csv
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12585 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157546 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 182693.4 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 2 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12585 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157546 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 182693.4 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 2 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12584 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157603 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 153619.4 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12596 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157725 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 198781.1 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12594 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157751 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 176868.9 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12594 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157751 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 176868.9 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12594 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157717 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 205692 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12594 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157751 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 176868.9 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12585 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157546 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 177536.4 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12596 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157763 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 172901 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12596 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157763 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 172901 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 12596 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157763 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 172901 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 1 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 11634 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 154393 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 155454.2 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 9 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 160761.9 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 164771.2 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 5 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 160761.9 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 164771.2 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 5 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 156373.6 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 159280.3 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 5 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10262 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 156953 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 155748.4 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 5 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 156279.6 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157444.5 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 4 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 155207.8 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 151453 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 4 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 11634 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 154393 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 154476.5 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 4 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 154950.7 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 157002.4 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 4 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 153214.7 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 148687 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 4 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 155994.6 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 158502 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 4 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable)))
    (seed.branch.abcd::fx
     (app.chart:span
      (seed.branch.abcd::fx "line" (:fx :uicc-select) (:type :select)
       (:options "line" "retraceX" "retraceY"))
      (seed.branch.abcd::fx (nth 0 '(:none :left :right :both))
       (:fx :uicc-button) (:type)
       (:role (uir-toggle :symap '(:| ∘─∘ | :|─∘─∘ | :| ∘─∘─| :─∘─∘─))))
      (seed.branch.abcd::fx 10079 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 153214.7 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 15119 (:fx :uicc-field) (:type :numeric :integer))
      (seed.branch.abcd::fx 148687 (:fx :uicc-field) (:type :numeric :float))
      (seed.branch.abcd::fx 4 (:fx :uicc-field) (:type :numeric :float)))
     (:fx :uic-series :layout (:groups :rows (-2 4 2)))
     (:role uir-call-form (uir-reducable))))
   (:fx :uic-series :layout (:groups :rows (1)))
   (:role uir-call-form uir-reducable (uir-call :n :populate))))
 (:fx :uic-series :layout (:groups :rows (-2))) (:type :called :removable)
 (:role uir-call-form uir-reducable (uir-sortable :range 2)))
