(IN-PACKAGE #:DEMO-MARKET)
(DEFVAR CHART-ENTITIES)
(META
 (SETQ CHART-ENTITIES
         (LIST
          (LIST :TYPE "line" :POINTS
                (LIST (LIST 1087455600 1.52) (LIST 1087650000 1.48)))))
 :MODE
 (:VALUE NIL :FORMAT :CHART-ENTITIES-EXPAND :OPTIONS
  ((:VALUE
    (META
     ((META "" :MODE (:VALUE "" :VIEW :TEXTFIELD :TITLE "Start Time"))
      (META "" :MODE (:VALUE "" :VIEW :TEXTFIELD :TITLE "Start Price"))
      (META "" :MODE (:VALUE "" :VIEW :TEXTFIELD :TITLE "End Time"))
      (META "" :MODE (:VALUE "" :VIEW :TEXTFIELD :TITLE "End Price"))
      (META "" :MODE (:VALUE "" :VIEW :TEXTFIELD :TITLE "APL" :REMOVABLE T)
	    :NAME :APPLY-APL))
     :EACH (:VISIBLE-MEMBERS ((:NAME :APPLY-APL :TITLE "Apply APL" :STATE :OFF)))
     :MODE (:VIEW :ITEM :TITLE "Line" :REMOVABLE T :OPEN T :FORMAT-PROPERTIES (:TYPE :LOAD) :TOGGLE :ON
		  :OPTIONS ((:TITLE "Apply APL" :ACTION :TOGGLE-VISIBILITY :NAME :APPLY-APL))))
    :TITLE "Line"))
  :REMOVABLE NIL :FILL-BY :SELECT :VIEW :LIST :MODEL
  ((META
    ((META "1087455600" :MODE
      (:VALUE "1087455600" :VIEW :TEXTFIELD :TITLE "Start Time"))
     (META "1.52" :MODE (:VALUE "1.52" :VIEW :TEXTFIELD :TITLE "Start Price"))
     (META "1087650000" :MODE
      (:VALUE "1087650000" :VIEW :TEXTFIELD :TITLE "End Time"))
     (META "1.48" :MODE (:VALUE "1.48" :VIEW :TEXTFIELD :TITLE "End Price")))
    :MODE
    (:VALUE NIL :MODEL
     ((META "1087455600" :MODE
       (:VALUE "1087455600" :VIEW :TEXTFIELD :TITLE "Start Time"))
      (META "1.52" :MODE (:VALUE "1.52" :VIEW :TEXTFIELD :TITLE "Start Price"))
      (META "1087650000" :MODE
       (:VALUE "1087650000" :VIEW :TEXTFIELD :TITLE "End Time"))
      (META "1.48" :MODE (:VALUE "1.48" :VIEW :TEXTFIELD :TITLE "End Price")))
     :FORMAT-PROPERTIES (:TYPE :LINE) :TOGGLE :ON :REMOVABLE T :OPEN T :TITLE
     "Line" :VIEW :ITEM)))))
