(IN-PACKAGE #:DEMO-MARKET)
(DEFVAR CHART-ENTITIES)
(META (SETQ CHART-ENTITIES (LIST)) :MODE
 (:MODEL
  ((META
    ((META "1087455600" :MODE
      (:TITLE "Start Time" :VIEW :TEXTFIELD :VALUE "1087455600"))
     (META "1.52" :MODE (:TITLE "Start Price" :VIEW :TEXTFIELD :VALUE "1.52"))
     (META "1087650000" :MODE
      (:TITLE "End Time" :VIEW :TEXTFIELD :VALUE "1087650000"))
     (META "1.48" :MODE (:TITLE "End Price" :VIEW :TEXTFIELD :VALUE "1.48")))
    :MODE
    (:VALUE NIL :MODEL
     ((META "1087455600" :MODE
       (:TITLE "Start Time" :VIEW :TEXTFIELD :VALUE "1087455600"))
      (META "1.52" :MODE (:TITLE "Start Price" :VIEW :TEXTFIELD :VALUE "1.52"))
      (META "1087650000" :MODE
       (:TITLE "End Time" :VIEW :TEXTFIELD :VALUE "1087650000"))
      (META "1.48" :MODE (:TITLE "End Price" :VIEW :TEXTFIELD :VALUE "1.48")))
     :FORMAT-PROPERTIES (:TYPE :LOAD) :TOGGLE :ON :OPEN T :REMOVABLE T :TITLE
     "Line" :VIEW :ITEM))
   (META
    ((META "1089118800" :MODE
      (:TITLE "Start Time" :VIEW :TEXTFIELD :VALUE "1089118800"))
     (META "1.5304275" :MODE
      (:TITLE "Start Price" :VIEW :TEXTFIELD :VALUE "1.5304275"))
     (META "1089223200" :MODE
      (:TITLE "End Time" :VIEW :TEXTFIELD :VALUE "1089223200"))
     (META "1.5019635" :MODE
      (:TITLE "End Price" :VIEW :TEXTFIELD :VALUE "1.5019635")))
    :MODE
    (:VALUE NIL :MODEL
     ((META "1089118800" :MODE
       (:TITLE "Start Time" :VIEW :TEXTFIELD :VALUE "1089118800"))
      (META "1.5304275" :MODE
       (:TITLE "Start Price" :VIEW :TEXTFIELD :VALUE "1.5304275"))
      (META "1089223200" :MODE
       (:TITLE "End Time" :VIEW :TEXTFIELD :VALUE "1089223200"))
      (META "1.5019635" :MODE
       (:TITLE "End Price" :VIEW :TEXTFIELD :VALUE "1.5019635")))
     :FORMAT-PROPERTIES (:TYPE :LOAD) :TOGGLE :ON :OPEN T :REMOVABLE T :TITLE
     "Line" :VIEW :ITEM)))
  :VIEW :LIST :FILL-BY :SELECT :REMOVABLE NIL :OPTIONS
  ((:TITLE "Line" :VALUE
    (META
     ((META "" :MODE (:TITLE "Start Time" :VIEW :TEXTFIELD :VALUE ""))
      (META "" :MODE (:TITLE "Start Price" :VIEW :TEXTFIELD :VALUE ""))
      (META "" :MODE (:TITLE "End Time" :VIEW :TEXTFIELD :VALUE ""))
      (META "" :MODE (:TITLE "End Price" :VIEW :TEXTFIELD :VALUE ""))
      (META "" :NAME :APPLY-APL :MODE
       (:REMOVABLE T :TITLE "APL" :VIEW :TEXTFIELD :VALUE "")))
     :EACH
     (:VISIBLE-MEMBERS ((:NAME :APPLY-APL :TITLE "Apply APL" :STATE :OFF)))
     :MODE
     (:VIEW :ITEM :TITLE "Line" :REMOVABLE T :OPEN T :FORMAT-PROPERTIES
      (:TYPE :LOAD) :TOGGLE :ON :OPTIONS
      ((:TITLE "Apply APL" :ACTION :TOGGLE-VISIBILITY :NAME :APPLY-APL))))))
  :FORMAT :CHART-ENTITIES-EXPAND :VALUE NIL))
